name: Generate Pac-Man Demo GIF

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo, persist the GITHUB_TOKEN for pushes
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # <— allows later git push to authenticate
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run the Pac-Man recording script
      - name: Generate Pac-Man demo GIF
        run: npm run generate:gif
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      # 5. Commit and push the generated GIF
      - name: Commit and push demo GIF
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/pacman-demo.gif
          git diff --quiet || git commit -m "ci: update Pac-Man demo [skip ci]"
          git push
        # No explicit token here because credentials are already persisted
