# .github/workflows/pacman-animation.yml
name: Generate Pac-Man Demo GIF

on:
  schedule:
    - cron: '0 0 * * *'        # daily at midnight UTC
  workflow_dispatch:           # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js (for Puppeteer & GIFEncoder)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run the Pac-Man recording script
      - name: Generate Pac-Man demo GIF
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: npm run generate:gif

      # 5. Commit and push the generated GIF
      - name: Commit demo GIF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/pacman-demo.gif
          git diff --quiet && echo "No changes to commit" || git commit -m "ci: update Pac-Man demo [skip ci]"
          git push origin main
