# .github/workflows/pacman-animation.yml
name: Generate Pac-Man Demo GIF

# grant write access to repo contents
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Generate Pac-Man demo GIF
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: npm run generate:gif

      - name: Commit and push demo GIF
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/pacman-demo.gif
          git diff --quiet || git commit -m "ci: update Pac-Man demo [skip ci]"
          git push
